app:
  name: "go-web"
  mode: "dev"
  port: "8000"
  version: "1.0"

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "hrdbms"
  max_open_conns: 20
  max_Idle_conns: 10
